<?php

namespace CommitStripBundle\Repository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMinId()
    {
        $qb = $this->createQueryBuilder('c');
        $query = $qb->select($qb->expr()->min('c.nbcard'))
                    ->getQuery();
        $result = $query->getScalarResult();
        return $result[0][1];
    }

    public function getMaxId()
    {
        $qb = $this->createQueryBuilder('c');
        $query = $qb->select($qb->expr()->max('c.nbcard'))
                    ->getQuery();
        $result = $query->getScalarResult();
        return $result[0][1];
    }

    public function getNextCard($id)
    {
        $maxid = $this->getMaxId();

        if ($id >= $maxid) {
            return $this->find($maxid);
        }

        $card = $this->find($id);
        $nextCard = null;
        $nbCard = $card->getNbcard()+1;
        while (empty($nextCard)) {
            $nextCard = $this->findBy(['nbcard' => $nbCard]);
            $nbCard++;
        }

        return $nextCard[0];
    }

    public function getPrevCard($id)
    {
        $minid = $this->getMinId();

        if ($id <= $minid) {
            return $this->find($minid);
        }

        $card = $this->find($id);
        $prevCard = null;
        $nbCard = $card->getNbcard()-1;
        while (empty($prevCard)) {
            $prevCard = $this->findBy(['nbcard' => $nbCard]);
            $nbCard--;
        }

        return $prevCard[0];
    }
}
