subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

nlf_commit_strip:
    resource: "@NLFCommitStripBundle/Resources/config/routing.yml"
    prefix:   /story/



