commit_strip:
    resource: "@CommitStripBundle/Controller/"
    type:     annotation
    prefix:   /commitstrip

subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

