commit_strip_commit_strip:
    resource: "@CommitStripCommitStripBundle/Controller/"
    type:     annotation
    prefix:   /

subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

