commit_strip_homepage:
    path:     /story/{id}
    defaults:
        _controller: CommitStripBundle:Default:index
        id:      1
commit_strip_add:
    path:      /add
    defaults:  { _controller: CommitStripBundle:Default:add }
oc_platform_home:
    path:      /form
    defaults:  { _controller: CommitStripBundle:Default:form }